### PR TITLE
complete EDA

### PR DESCRIPTION
**Pull request by MDSFusionist**
Dear Team, I have completed the exploratory data analysis (EDA) for our project. For each section, I've included a brief interpretation to guide our understanding of the dataset's characteristics. Currently, I have retained observations with null values. This will allow us to collaboratively decide on the best imputation methods or to drop them during our pipeline construction in the next stage of our project.

### CODE REVIEW

**Comment by sandygross** [comment]
Great job, Doris! Thanks!
-  I would suggest that we add titles to the figures. 
- The scatterplot suffers from over plotting. But I think the relationship between SBP AND DBP is really interesting. Maybe we create two heatmaps for this specific relationship, one for people with the disease and then for the ones who have not. 
- We should also decide on how we want to proceed with NAs

**Comment by MDSFusionist** [comment]
@sandygross Thanks for your feedback. I will improve the data visualization in the EDA section later. For the missing values, my suggestion will be to use imputation when you set up the preprocessor.

**Comment by sandygross** [comment]
Hi Doris, I just saw that u created a new commit. First of all thanks! I just saw that for figure "distribution of target feature" the add on "figure 1" is missing. I think Tiffany also wanted all the tables such as the correlation Matrix or the Data Frames to have a figure/table number. Would be great, if you could add that as well!

**Comment by MDSFusionist** [comment]
@sandygross I saw you fixed the missing title in the final report. Thank you. Let's leave this branch alone since it is redundant now.

**Pull request closed without merging**
