### PR TITLE
update README file

### PR DESCRIPTION
**Pull request by MDSFusionist**
Dear team, I have updated the README file to include more detailed information about our project, including installation instructions, data source description, and usage guidelines. This is a template that I used before for work and I also accommodate course example. Please review these changes and feel free to make any modifications you deem necessary to improve clarity or accuracy.

### CODE REVIEW

**Comment by hema2022ubc** [comment]
Hi Doris, thank you for your work. I  also update the the README.md in my branch locally, should we merge this to the main first or I modify the README.md on your base then we merge the final version to the main?

**Comment by MDSFusionist** [comment]
@hema2022ubc Hi He, how about compiling them together later once we finish the html report?

**Comment by sandygross** [comment]
Hi Doris, thanks a lot for your work. I really like the layout. For the Project Overview we should only keep in mind that I added KNN as well not only Logistic Regression. 
I would suggest that we meet tomorrow after class and do the final adjustments/merging. What do you think?

**Comment by sandygross** [comment]
Also thanks to you, He! This is a great introduction to a our project

**Pull request merged**
